---
# tasks file for node-exporter

- name: Create node_exporter user
  user:
    name: node_exporter
    comment: node_exporter user
    shell: /bin/false
    state: present

- name: Download node_exporter binary
  get_url:
    url: https://github.com/prometheus/node_exporter/releases/download/v{{node_exporter_version}}/node_exporter-{{node_exporter_version}}.linux-amd64.tar.gz
    dest: /tmp
    mode: '0755'

- name: Extract node_exporter binary
  unarchive:
    src: /tmp/node_exporter-{{node_exporter_version}}.linux-amd64.tar.gz
    dest: /tmp
    remote_src: yes

- name: Copy binary to destination folder
  copy:
    src: /tmp/node_exporter-{{node_exporter_version}}.linux-amd64/node_exporter
    dest: /usr/local/bin
    owner: node_exporter
    group: node_exporter
    mode: '0755'
    remote_src: yes

- name: Install node_exporter systemd unit file
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service

- name: Start node_exporter
  systemd:
    name: node_exporter
    state: started
    daemon_reload: yes
